name = "eqt-feedback-api"
main = "src/index.ts"
compatibility_date = "2026-06-29"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "eqt-feedback-db"
# Replace with actual D1 database ID after create
database_id = "a58d4980-8ea3-4c30-8368-b1ba871d9acd"

# R2 Bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "eqt-feedback-bucket"

[vars]
TELEGRAM_BOT_TOKEN = "8981665918:AAFjSEXkxAwuG6LNMEBdCVrLU0KVIs8S1h4"
# Set to the target Chat ID or Channel ID where notifications will be sent
TELEGRAM_CHAT_ID = "1880182104" 

routes = [
  { pattern = "feedback.eqt.net.im/goal", custom_domain = true },
  { pattern = "feedback.eqt.net.im/image/*", custom_domain = true }
]
