name = "eqt-drm-api"
main = "src/index.ts"
compatibility_date = "2026-06-19"

# D1 Database binding. DB is bound in the code.
[[d1_databases]]
binding = "DB"
database_name = "eqt-drm-db"
# Replace with your actual D1 Database ID after running `wrangler d1 create eqt-drm-db`
database_id = "f77e30fd-6dee-4062-a916-e8f4f717036d"

[vars]
MAIL_SENDER = "noreply@eqt.net.im"
MAIL_SENDER_PASSWORD = "q4W62}bWtR"
MAIL_SEND_SERVER = "smtpserver.301098.xyz"
MAIL_SEND_SAFE_PORT = "465"
TEST_MAIL_RECEIVER = "tmp@301098.xyz"

routes = [
  { pattern = "lic.eqt.net.im", custom_domain = true },
  { pattern = "download.eqt.net.im", custom_domain = true }
]


