// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {server} from '../models';

export function ActivateLicense(arg1:string):Promise<void>;

export function AgentStatus():Promise<main.AgentStatus>;

export function AppInfo():Promise<main.AppInfo>;

export function CancelChatDownload(arg1:string):Promise<void>;

export function Chat():Promise<main.AgentStatus>;

export function ChatSaveDirectory():Promise<string>;

export function CheckCrashReport():Promise<main.CrashReportInfo>;

export function CheckForUpdates():Promise<main.GUIUpdateCheckResult>;

export function ClearHistory():Promise<void>;

export function ClearPendingUpdate():Promise<void>;

export function DevForceOnlineLicenseSync():Promise<main.AgentStatus>;

export function DevTriggerCrash():Promise<main.CrashReportInfo>;

export function DismissCrashReport():Promise<void>;

export function DismissCrashReportPermanently():Promise<void>;

export function DownloadChatAttachment(arg1:string,arg2:string):Promise<string>;

export function DownloadUpdate(arg1:main.GUIUpdateCheckResult):Promise<string>;

export function ExportDiagnosticsZip():Promise<string>;

export function GenerateQRCodePNG(arg1:string,arg2:number):Promise<string>;

export function GetCrashReportDetail():Promise<main.CrashReportDetail>;

export function GetFileInfos(arg1:Array<string>):Promise<Array<main.GUIFileInfo>>;

export function GetLogFiles():Promise<Array<main.LogFileInfo>>;

export function GetLogTail(arg1:number):Promise<Array<string>>;

export function GetPendingOfflineUpdate():Promise<server.PendingOfflineUpdateInfo>;

export function InstallUpdate(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function ReadSettings():Promise<main.DesktopSettings>;

export function Receive(arg1:string):Promise<main.AgentStatus>;

export function RefreshLicenseStatus():Promise<main.AgentStatus>;

export function RepeatTask(arg1:number):Promise<main.AgentStatus>;

export function ResetLicense():Promise<void>;

export function RestartAgent():Promise<void>;

export function RightClickIntegrationStatus():Promise<main.DesktopIntegrationStatus>;

export function SaveChatAttachmentAs(arg1:string,arg2:string):Promise<string>;

export function SaveChatAttachments(arg1:Array<string>,arg2:Array<string>,arg3:Array<string>):Promise<Array<main.ChatAttachmentSaveResult>>;

export function SaveSettings(arg1:main.DesktopSettings):Promise<main.DesktopSettings>;

export function SaveSharePosterImage(arg1:string):Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectLogDirectory():Promise<string>;

export function SelectReceiveDirectory():Promise<string>;

export function SelectShareDirectory():Promise<string>;

export function SetAutoStop(arg1:boolean):Promise<main.AgentStatus>;

export function SetPaidStatus(arg1:boolean,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetRightClickIntegrationEnabled(arg1:boolean):Promise<main.DesktopIntegrationStatus>;

export function Share(arg1:Array<string>):Promise<main.AgentStatus>;

export function ShutdownAgent():Promise<void>;

export function StopChat():Promise<void>;

export function StopClientTransfer(arg1:string):Promise<boolean>;

export function StopCurrent():Promise<void>;

export function SubmitCrashReport():Promise<string>;

export function SubmitFeedback(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ValidateFreeTier(arg1:Array<string>):Promise<string>;
