// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function AgentStatus() {
  return window['go']['main']['App']['AgentStatus']();
}

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CancelChatDownload(arg1) {
  return window['go']['main']['App']['CancelChatDownload'](arg1);
}

export function Chat() {
  return window['go']['main']['App']['Chat']();
}

export function ChatSaveDirectory() {
  return window['go']['main']['App']['ChatSaveDirectory']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DevForceOnlineLicenseSync() {
  return window['go']['main']['App']['DevForceOnlineLicenseSync']();
}

export function DevSetUsedSeconds(arg1) {
  return window['go']['main']['App']['DevSetUsedSeconds'](arg1);
}

export function DownloadChatAttachment(arg1, arg2) {
  return window['go']['main']['App']['DownloadChatAttachment'](arg1, arg2);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GetFileInfos(arg1) {
  return window['go']['main']['App']['GetFileInfos'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function Receive(arg1) {
  return window['go']['main']['App']['Receive'](arg1);
}

export function RefreshLicenseStatus() {
  return window['go']['main']['App']['RefreshLicenseStatus']();
}

export function RepeatTask(arg1) {
  return window['go']['main']['App']['RepeatTask'](arg1);
}

export function ResetLicense() {
  return window['go']['main']['App']['ResetLicense']();
}

export function RestartAgent() {
  return window['go']['main']['App']['RestartAgent']();
}

export function RightClickIntegrationStatus() {
  return window['go']['main']['App']['RightClickIntegrationStatus']();
}

export function SaveChatAttachmentAs(arg1, arg2) {
  return window['go']['main']['App']['SaveChatAttachmentAs'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectLogDirectory() {
  return window['go']['main']['App']['SelectLogDirectory']();
}

export function SelectReceiveDirectory() {
  return window['go']['main']['App']['SelectReceiveDirectory']();
}

export function SelectShareDirectory() {
  return window['go']['main']['App']['SelectShareDirectory']();
}

export function SetAutoStop(arg1) {
  return window['go']['main']['App']['SetAutoStop'](arg1);
}

export function SetPaidStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPaidStatus'](arg1, arg2, arg3, arg4);
}

export function SetRightClickIntegrationEnabled(arg1) {
  return window['go']['main']['App']['SetRightClickIntegrationEnabled'](arg1);
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}

export function Share(arg1) {
  return window['go']['main']['App']['Share'](arg1);
}

export function ShutdownAgent() {
  return window['go']['main']['App']['ShutdownAgent']();
}

export function StartupStatus() {
  return window['go']['main']['App']['StartupStatus']();
}

export function StopChat() {
  return window['go']['main']['App']['StopChat']();
}

export function StopCurrent() {
  return window['go']['main']['App']['StopCurrent']();
}

export function SubmitFeedback(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SubmitFeedback'](arg1, arg2, arg3, arg4, arg5);
}

export function ValidateFreeTier(arg1) {
  return window['go']['main']['App']['ValidateFreeTier'](arg1);
}
