// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateLicense(arg1:string):Promise<void>;

export function AgentStatus():Promise<main.AgentStatus>;

export function AppInfo():Promise<main.AppInfo>;

export function Chat():Promise<main.AgentStatus>;

export function ChatSaveDirectory():Promise<string>;

export function CheckForUpdates():Promise<main.GUIUpdateCheckResult>;

export function ClearHistory():Promise<void>;

export function DownloadChatAttachment(arg1:string,arg2:string):Promise<string>;

export function DownloadUpdate(arg1:main.GUIUpdateCheckResult):Promise<string>;

export function InstallUpdate(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ReadSettings():Promise<main.DesktopSettings>;

export function Receive(arg1:string):Promise<main.AgentStatus>;

export function RepeatTask(arg1:number):Promise<main.AgentStatus>;

export function ResetLicense():Promise<void>;

export function RestartAgent():Promise<void>;

export function RightClickIntegrationStatus():Promise<main.DesktopIntegrationStatus>;

export function SaveChatAttachmentAs(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:main.DesktopSettings):Promise<main.DesktopSettings>;

export function SelectFiles():Promise<Array<string>>;

export function SelectReceiveDirectory():Promise<string>;

export function SelectShareDirectory():Promise<string>;

export function SetPaidStatus(arg1:boolean,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetRightClickIntegrationEnabled(arg1:boolean):Promise<main.DesktopIntegrationStatus>;

export function SetStartupEnabled(arg1:boolean):Promise<main.DesktopIntegrationStatus>;

export function Share(arg1:Array<string>):Promise<main.AgentStatus>;

export function ShutdownAgent():Promise<void>;

export function StartupStatus():Promise<main.DesktopIntegrationStatus>;

export function StopChat():Promise<void>;

export function StopCurrent():Promise<void>;
