// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgentStatus():Promise<main.AgentStatus>;

export function OpenURL(arg1:string):Promise<void>;

export function ReadSettings():Promise<main.DesktopSettings>;

export function Receive(arg1:string):Promise<main.AgentStatus>;

export function RestartAgent():Promise<void>;

export function SaveSettings(arg1:main.DesktopSettings):Promise<main.DesktopSettings>;

export function SelectFiles():Promise<Array<string>>;

export function SelectReceiveDirectory():Promise<string>;

export function SelectShareDirectory():Promise<string>;

export function Share(arg1:Array<string>):Promise<main.AgentStatus>;

export function StopCurrent():Promise<void>;
