// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentStatus() {
  return window['go']['main']['App']['AgentStatus']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function Receive(arg1) {
  return window['go']['main']['App']['Receive'](arg1);
}

export function RepeatTask(arg1) {
  return window['go']['main']['App']['RepeatTask'](arg1);
}

export function RestartAgent() {
  return window['go']['main']['App']['RestartAgent']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectReceiveDirectory() {
  return window['go']['main']['App']['SelectReceiveDirectory']();
}

export function SelectShareDirectory() {
  return window['go']['main']['App']['SelectShareDirectory']();
}

export function Share(arg1) {
  return window['go']['main']['App']['Share'](arg1);
}

export function StopCurrent() {
  return window['go']['main']['App']['StopCurrent']();
}
